# -*- coding: utf-8 -*-
"""1120913_4120E003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dsr1pDSi_gg65BIDcuqBvePC3Y2LIndW
"""

a=int(input('enter nuber A : '))
b=int(input('enter nuber B : '))
print('A^b = ',a**b)